### PR TITLE
Horizon: the `README.md and stuff` update

### PR DESCRIPTION
**Pull request by XDRwastaken**
# Description

Some "Quality Of Li-
Okay fine i'm really just fixing your `README.md`

## Issue(s) Solved 
null

## Type of change

nada

# How Has This Been Tested?

wahuh?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my chnages are stable
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tristanpoland** [comment]
Looks great thanks for the updates!

**Comment by tristanpoland** [comment]
> wait-

Force of habit, sorry 😆

**Comment by WilliamAnimate** [comment]
> i'm not done-

talk is cheap, show me the code
:trollface:

**Review by WilliamAnimate — APPROVED** [review]
lgtm

**Pull request merged**
