### PR TITLE
WIP: 141 add compile time plugin system

### LINKED ISSUE #141: Add Compile-time Macro and Function Override System to Horizon
# Add Compile-time Macro and Function Override System to Horizon

We need to make Horizon more flexible for plugins, especially the Horizon Enterprise plugin. Right now, we can't override core stuff like the `define_event` macro. This PR aims to fix that with a compile-time solution.

## What's the problem?

1. Plugins can't modify or extend core Horizon functions and macros.
2. The Enterprise plugin specifically needs to override `define_event` for advanced event handling, logging, and auth.

## What's the plan?

1. Create a compile-time override system that lets plugins:
   - Redefine existing macros
   - Wrap functions with extra logic
   - Replace functions entirely

2. Focus on making `define_event` overridable for the Enterprise plugin.

## How we'll do it:

1. New `override_system` module using procedural macros
2. `define_overridable_macro!` to make macros overridable at compile-time
3. Function wrapping system using traits and static dispatch
4. Plugin-specific code generation at compile-time
5. Update the build process to incorporate plugin overrides

## Why this matters:

- Makes Horizon way more extensible
- Lets us build powerful plugins like Enterprise without messing with core code
- Easier updates and maintenance
- No runtime performance hit since all overrides are resolved at compile-time

## Challenges we might face:

- Keeping things backwards compatible
- Potential increase in compile times
- Ensuring clear error messages for override conflicts

## Next up:

1. Design diagram for the compile-time override system (We should hold a meeting on Discord for this)
2. Prototype focusing on `define_event`
3. Thorough testing, including compile-time error scenarios
4. Docs for plugin devs on using the new override capabilities

This is a big step for Horizon, especially for enterprise users. It'll make our lives easier when building advanced plugins and give users more ways to customize Horizon for their needs, all without sacrificing runtime performance.

Thoughts? Let's discuss!

### PR DESCRIPTION
**Pull request by tristanpoland**
# Description
This PR implements a compile-time macro and function override system for Horizon. It allows plugins, particularly the Horizon Enterprise plugin, to override and extend core functionalities like the `define_event` macro without runtime performance impact.

## Issue(s) Solved 
Fixes #141

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
- [ ] Test A: Compile-time override of `define_event` macro
- [ ] Test B: Plugin function wrapping with static dispatch
- [ ] Test C: Backwards compatibility with existing Horizon implementations
- [ ] Test D: Compile-time error handling for conflicting overrides

**Test Configuration**:
* Firmware version: N/A
* Hardware: HCE Dev Container
* Toolchain: HCE Dev Container version

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my changes are stable
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tristanpoland** [comment]
@haywoodspartan @WilliamAnimate @Tuafo @IchoTM We should find a time to meet in a call as a group and research how this is done. If you guys have any days coming up on the weekends or in the evenings where this is possible please let me know!

**Comment by IchoTM** [comment]
@tristanpoland 
I'm open pretty much whenever but next weekend I will be at MHacks so I'm kinda mentally peeping for that I'm also busy this upcoming thursday but outside of that I'm available whenever the rest of the team is.

**Comment by WilliamAnimate** [comment]
> @haywoodspartan @WilliamAnimate @Tuafo @IchoTM We should find a time to meet in a call as a group and research how this is done. If you guys have any days coming up on the weekends or in the evenings where this is possible please let me know!

I believe I will be available on Saturdays, all day.

**Comment by tristanpoland** [comment]
Tomorrow at noon EST work for you then @haywoodspartan @Tuafo @IchoTM ?

**Comment by tristanpoland** [comment]
During the meeting with the folks I pinged again and the open-source contribs who were able to join we decided on integrating this plugin system into Horizon [https://github.com/Far-Beyond-Dev/Rust-Plugin-Engine](https://github.com/Far-Beyond-Dev/Rust-Plugin-Engine), this will take place over the next couple of weeks and we would love any help you can all provide!

All work on this should be merged to this PR's dedicated branch which (when stable) will be merged into the main branch primary discussion should take place here for the sake of those who are not in Discord and for archival purposes

Thanks all, let's get coding!!
-- Trident

**Review by WilliamAnimate — APPROVED** [review]
lgtm

**Review by haywoodspartan — COMMENTED** [review]
Learned rust in 3 hours

**Review by IchoTM — COMMENTED** [review]
Looks good to me.

**Pull request merged**
